### ISSUE TITLE
Reporte

### ISSUE THREAD

**Issue by christopheremv** [SistemasTecTlaxiaco/practica-de-hilos-christopheremv#2]
[reporte hilos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-christopheremv/files/6497869/reporte.hilos.pdf)

**Comment by Aricel117** [comment]
calif: 18

**Comment by josealfredo79** [comment]
Hay que realizar un reporte mas detallado y estructurado, para la próxima no se evalua

**Comment by josealfredo79** [comment]
Revisado
